{% set name = "icecream" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0aa4a7c3374ec36153a1d08f81e3080e83d8ac1eefd97d2f4fe9544e8f9b49de

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - colorama >=0.3.9
    - pygments >=2.2.0
    - executing >=0.3.1
    - asttokens >=2.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}

about:
  home: https://github.com/gruns/icecream
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: |
    Never use print() to debug again; inspect variables, expressions,
    and program execution with a single, simple function call.

  description: |
    Do you ever use print() or log() to debug your code? Of course you do.
    IceCream, or ic for short, makes print debugging a little sweeter.

    ic() is like print(), but better:

    1. It prints both expressions/variable names and their values.
    2. It's 40% faster to type.
    3. Data structures are pretty printed.
    4. Output is syntax highlighted.
    5. It optionally includes program context: filename, line number, and parent function.

extra:
  recipe-maintainers:
    - alexmojaki
